### PR TITLE
Add development notes

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@fh wdyt?

**Comment by fh** [comment]
:+1: Maybe adjust https://github.com/phinze/landrush/blob/master/.travis.yml#L20, too, while you are at it - the new version requirement seems to be [`<= 1.10.5`](https://github.com/mitchellh/vagrant/blob/v1.7.4/vagrant.gemspec#L18).

lgtm otherwise.

**Comment by njam** [comment]
Oh missed that!

Like this?

**Comment by fh** [comment]
good to merge. :)

**Pull request merged**
