### PR TITLE
Travis improvements

### PR DESCRIPTION
**Pull request by fh**
Faster travis runs:

* Uses docker container
* Uses system libs for nokogiri
* Caches bundler data

Also no longer emails on test success

### CODE REVIEW

**Comment by njam** [comment]
lvgtm!

**Comment by njam** [comment]
Maybe add `\n` on the last line?
Good to merge?

**Comment by fh** [comment]
@njam Added linebreak, good to merge, if you want to.

**Comment by njam** [comment]
Ok let's merge!
It's your pull request :P

**Comment by fh** [comment]
Ah, ok, sorry. I am used to the "PR is merged by someone else after review" approach =)

**Pull request merged**
