### PR TITLE
Improve CONTRIBUTING guidelines

### PR DESCRIPTION
**Pull request by strzibny**
* List of maintainers is now a list
* Grammar corrections

### CODE REVIEW

**Comment by njam** [comment]
It's a pity github usernames are not linked, but I think it's not possible…

lgtm

**Comment by strzibny** [comment]
Edited to include the links.

**Comment by njam** [comment]
Makes sense :)

**Comment by bexelbie** [comment]
This would invalidate #150 - we need to just make a choice.

**Comment by njam** [comment]
Either branch is okay :)
I would rather go with this one, as it has the links for the usernames?

**Comment by bexelbie** [comment]
LGTM

**Pull request merged**
