### PR TITLE
Update of README/CONTRIBUTING b/c new maintainers

### LINKED ISSUE #139: New Maintainers!
I have received word from several wonderful humans interested in helping pick up maintainer work on this project. Hooray!

Highlighting all of you so we can coordinate a bit:

 * @njam
 * @ahpook 
 * @strzibny 
 * @fh
 * @bexelbie

You're also all added as collaborators on the project as well. To be clear, nobody has actually accepted any responsibility here - this is just the initial broadcast to all those who expressed interest. Any of you can feel free to opt out at any point. :+1: 

As I mentioned, I'm pretty over allocated right now and have had precious little time for poor `landrush`. They say that the first step to finding a solution is admitting you have a problem. :grinning: 

I have no specific agenda for the project, so I'll leave it to you to talk about what's next. 

Here are some initial topic suggestions to kick things off:

 * Issue triage
 * Prioritizing important bugs / features 
 * Discussing whether or not to move the github repo to its own org - happy to do that if you folks would like

Welcome and thank you!

p.s. Anybody I missed who is interested in joining in just highlight me and I'll get you added as a collaborator and this discussion.

### PR DESCRIPTION
**Pull request by bexelbie**
Fixes #139

### CODE REVIEW

**Comment by njam** [comment]
lgtm

Maybe also remove the "unmaintained" notice from the readme, and link to this document at "Help Out!"?

**Comment by bexelbie** [comment]
@njam both of those were done.  Please see the updates to the README.

Given the nature of this change, I believe the majority of us should weigh in.  Opinons? @ahpook @strzibny and @fh ?

**Comment by njam** [comment]
lgtm

**Comment by fh** [comment]
:+1:

**Comment by bexelbie** [comment]
Lazy Consensus seems to be behind this.  I suggest we give @strzibny and @ahpook until the end of the day [CET] Friday.  @phinze you indicated you were stepping back - however I failed to mention you to see if you had an opinion here? I am also going to edit the file to include you as a maintainer to recover from that omission.

**Comment by phinze** [comment]
LGTM!

**Comment by ahpook** [comment]
:+1: from me

**Comment by bexelbie** [comment]
Merging ahead of "schedule" as we have 5 out of 6.  a/k/a invoking the Meatloaf rule.

**Pull request merged**
